[package]
name = "gdnative-sys"
version = "0.1.0"
authors = ["Matthew Collins <thethinkofdeath@gmail.com>"]
build = "build.rs"
workspace = ".."

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.30.0"
